language: node_js
node_js:
  - "12"
services:
  - mysql
before_script:
  - pwd
  - mkdir stats
  - mkdir stats/test
  - mkdir stats/rank
  - touch stats/rank/averageRank.json
  - touch stats/rank/singleRank.json
  - touch stats/test/test.json
  - echo "Please visit https://github.com/louismeunier/wca-stats-helper for more information" > stats/index.html
script:
  - source scripts/travis.sh
  - mysql -u root --password="" < scripts/sql/averageRankings.sql -ss > stats/rank/averageRank.json
  - mysql -u root --password="" < scripts/sql/singleRankings.sql -ss > stats/rank/singleRank.json
  - sudo apt install jsonlint
  - jsonlint stats/*.json
  - echo $1
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: stats
  target_branch: gh-pages
  on:
    branch: main