language: generic
services:
  - mysql
before_script:
  - pwd
  - mkdir stats
  - mkdir stats/test
  - mkdir stats/rank
  - mkdir stats/rank/averages
  - mkdir stats/rank/singles
  - mkdir stats/rank/tests
script:
  - source scripts/travis.sh
  - source scripts/createData.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: stats
  target_branch: gh-pages
  on:
    branch: main