sudo: true
language: generic
services:
  - mysql
before_script:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version 
  #- echo -e "[server]\nmax_allowed_packet=128M" | sudo tee -a /etc/mysql/conf.d/drupal.cnf
  #- sudo service mysql restart
  - pwd
  - mkdir stats
  - mkdir stats/test
  - mkdir stats/rank
  - mkdir stats/rank/averages
  - mkdir stats/rank/singles
  - mkdir stats/rank/tests
  - echo "<h1>404</h1><h2>Please see https://github.com/louismeunier/wca-stats-helper for help</h2>" > stats/404.html
script:
  - source scripts/travis.sh
  - source scripts/createData.sh
before_deploy:
  - source tests/sizeTest.sh
  - 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: stats
  target_branch: gh-pages
  on:
    branch: main