language: node_js
node_js:
  - "12"
services:
  - mysql
before_install:
  - source scripts/travis.sh
script:
  - mysql -u root --password="" < scripts/tests/test.sql
  - mysql -u root --password="" < scripts/rankings.sql 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: stats
  target_branch: gh-pages
  on:
    branch: main