language: node_js
node_js:
  - "12"
services:
  - mysql
before_script:
  - pwd
  - mkdir stats
  - mkdir stats/test
  - mkdir stats/averageRank
  - touch stats/averageRank/res.json
  - touch stats/test/test.json
script:
  - source scripts/travis.sh
  - mysql -u root --password="" < scripts/sql/tests/rankings_test.sql > -h stats/test/test.json
#- mysql -u root --password="" < scripts/sql/rankings.sql > -h stats/averageRank/res.json
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: stats
  target_branch: gh-pages
  on:
    branch: main