language: node_js
node_js:
  - "12"
services:
  - mysql
before_script:
  - pwd
  - echo -e "[mysqld]\nsecure_file_priv=\"\"" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart
  - mkdir /home/travis/build/louismeunier/wca-stats-helper/stats
  - chmod 755 /home/travis/build/louismeunier/wca-stats-helper/
  - chmod 755 /home/travis/build/louismeunier/wca-stats-helper/stats
script:
  - source scripts/travis.sh
  - mysql -u root --password="" < scripts/tests/test.sql
  - mysql -u root --password="" < scripts/rankings.sql 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: stats
  target_branch: gh-pages
  on:
    branch: main