on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
jobs:
  create_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install mysql & setup dirs
        working-directory: ./
        run: |
          sudo systemctl start mysql.service
          mkdir stats
          mkdir stats/test
          mkdir stats/rank
          mkdir stats/rank/averages
          mkdir stats/rank/singles
          mkdir stats/rank/tests
          echo "<h1>404</h1><h2>Please see https://github.com/louismeunier/wca-stats-helper for help</h2>" > stats/404.html
      - name: generate data
        working-directory: ./
        run: |
          source scripts/travis.sh
          source scripts/createData.sh
      - name: test
        working-directory: ./
        run: source tests/sizeTest.sh
      - name: commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update data"
          git push origin HEAD:gh-pages
